targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
      - test/**.dart
    builders:
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true