name: bloc_starter_project
description: "A starter Flutter project using bloc"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.3+1
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_i18n: ^0.33.0
  get_it: ^7.2.0
  i18n_extension: ^9.0.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  assets:
    - assets/translations/
  uses-material-design: true
